# Generated by Django 4.0.6 on 2023-09-24 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('flat_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('company', models.CharField(default='', max_length=100, verbose_name='Company')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='', max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(default='', max_length=10, verbose_name='Zip')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Country')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Phone Number')),
                ('amount', models.CharField(default='', max_length=100)),
                ('payment_method', models.CharField(default='', max_length=100)),
                ('transaction_type', models.CharField(default='', max_length=100, verbose_name='Transaction Type')),
                ('card_number', models.CharField(default='', max_length=16, verbose_name='Card Number')),
                ('exp_year', models.CharField(default='', max_length=5, verbose_name='Expiration Year')),
                ('exp_month', models.CharField(default='', max_length=5, verbose_name='Expiration Month')),
                ('cvv', models.CharField(default='', max_length=4, verbose_name='CVV')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Email')),
                ('transaction_id', models.CharField(default='', max_length=150, verbose_name='Transaction_id')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
