# Generated by Django 4.0.6 on 2023-10-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fees_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=500)),
                ('account_id', models.CharField(max_length=500)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('IFSC', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
