# Generated by Django 4.0.6 on 2023-08-21 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactions_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
