# Generated by Django 4.0.6 on 2023-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transactions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(default='', max_length=150, verbose_name='Transaction_id'),
        ),
    ]
