# Generated by Django 4.0.6 on 2023-10-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_userbanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=500)),
                ('bank_address', models.CharField(max_length=500)),
                ('account_number', models.CharField(default='09865645', max_length=500)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_holder_address', models.CharField(max_length=500)),
                ('routing_number', models.CharField(max_length=100)),
                ('bic_code', models.CharField(default='3454', max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
