# Generated by Django 4.0.6 on 2023-09-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='flat_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fees',
            name='percent',
            field=models.FloatField(),
        ),
    ]
