# Generated by Django 4.0.6 on 2023-08-26 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=100)),
                ('transactions', models.CharField(default='[]', max_length=50000000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
