# Generated by Django 4.0.6 on 2023-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchs',
            name='batch_id',
            field=models.IntegerField(default=1),
        ),
    ]
