# Generated by Django 4.0.6 on 2023-08-11 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
