# Generated by Django 4.0.6 on 2023-09-19 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access_token', '0002_alter_accesstoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('secret', models.CharField(default=uuid.uuid4, max_length=200)),
                ('key', models.CharField(default=uuid.uuid4, max_length=200)),
                ('account_id', models.IntegerField(default=100000)),
            ],
        ),
    ]
